version: "3.8"

volumes:
  kong_data: {}

services:
  kong:
    build:
      context: ./
    volumes:
      - ./kong.yml:/tmp/kong-declarative-config.yml
      - ./kong/plugins/totp-validator:/usr/local/lib/luarocks/rocks-5.1/kong-plugin-totp-validator/1.0.0-1/lua/kong/plugins/kong-plugin-totp-validator
      - ./kong/plugins/totp-validator:/usr/local/share/lua/5.1/kong/plugins/kong-plugin-totp-validator
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /tmp/kong-declarative-config.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_LOG_LEVEL: debug
      KONG_PLUGINS: bundled,kong-plugin-totp-validator
    ports:
      - 8000:8000
      - 8001:8001
      - 8444:8444
      - 8443:8443
