version: "3.8"

volumes:
  kong_data: {}

services:
  kong:
    build:
      context: ./
    volumes:
      - ./kong.yml:/tmp/kong-declarative-config.yml
      - ./kong/plugins/totp-validator:/usr/local/lib/luarocks/rocks-5.1/kong-plugin-totp-validator/0.1.0-1/lua/kong/plugins/kong-plugin-totp-validator
      - ./kong/plugins/totp-validator:/usr/local/share/lua/5.1/kong/plugins/kong-plugin-totp-validator
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /tmp/kong-declarative-config.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_LOG_LEVEL: debug
      KONG_PLUGINS: bundled,kong-plugin-totp-validator
    ports:
      - "9000:8000"
      - "9001:8001"
      - "9444:8444"
      - "9443:8443"

  vault:
    image: vault:1.11.3
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -dev -dev-listen-address=0.0.0.0:8200

  #Init totp engine from vault
  vault-init-totp:
    image: vault:1.11.3
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=root
    depends_on:
      - vault
    cap_add:
      - IPC_LOCK
    command: vault secrets enable totp

  httpbin:
    image: kennethreitz/httpbin
    ports:
      - "8080:80"
